[menus]
  [[menus.main]]
  	identifier = "home"  # 这是一个唯一的 ID,对应翻译里的ID
    name = 'Home'
    pageRef = '/'
    weight = 10

  [[menus.main]]
  	identifier = "categories"
    name = 'Categories'
    pageRef = '/categories'
    weight = 30

  [[menus.main]]
  	identifier = "tags"
    name = 'Tags'
    pageRef = '/tags'
    weight = 40

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
