baseURL = 'https://uncle-it.com/'
locale = 'zh-CN'
title = 'Uncle IT'
theme = 'uncleIt'

[params]
  logo = '/logo/logo256-round.png'
  description = "Uncle IT"

[languages]
  [languages.zh-CN]
  	languageCode = 'zh-CN'
    languageName = "中文"
    contentDir = "content/zh-CN" # 中文内容放在这里
    weight = 1
  [languages.en-US]
  	languageCode = 'en-US'
    languageName = "English"
    contentDir = "content/en-US"    # 英文内容放在这里
    weight = 2
